//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get2", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Get2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/java", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] java();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/java", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> javaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get4", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get5", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get6", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get6Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get7", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get7();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get7", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get7Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get8", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable Get8();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get8", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get8Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable FindUpdateEmployee(string upnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FindUpdateEmployeeAsync(string upnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmploye", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void DeleteEmploye(string delnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmploye", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteEmployeAsync(string delnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void AddEmployee(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task AddEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void UpdateEmployee(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] objects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> objectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsToArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] dsToArray();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsToArray", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> dsToArrayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable FindEmployee(string sosnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FindEmployeeAsync(string sosnr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WebApplication3.ServiceReference2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WebApplication3.ServiceReference2.WebService2Soap>, WebApplication3.ServiceReference2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public System.Data.DataTable Get1() {
            return base.Channel.Get1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get1Async() {
            return base.Channel.Get1Async();
        }
        
        public string[] Get2() {
            return base.Channel.Get2();
        }
        
        public System.Threading.Tasks.Task<string[]> Get2Async() {
            return base.Channel.Get2Async();
        }
        
        public object[] java() {
            return base.Channel.java();
        }
        
        public System.Threading.Tasks.Task<object[]> javaAsync() {
            return base.Channel.javaAsync();
        }
        
        public System.Data.DataTable Get3() {
            return base.Channel.Get3();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get3Async() {
            return base.Channel.Get3Async();
        }
        
        public System.Data.DataTable Get4() {
            return base.Channel.Get4();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get4Async() {
            return base.Channel.Get4Async();
        }
        
        public System.Data.DataTable Get5() {
            return base.Channel.Get5();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get5Async() {
            return base.Channel.Get5Async();
        }
        
        public System.Data.DataTable Get6() {
            return base.Channel.Get6();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get6Async() {
            return base.Channel.Get6Async();
        }
        
        public System.Data.DataTable Get7() {
            return base.Channel.Get7();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get7Async() {
            return base.Channel.Get7Async();
        }
        
        public System.Data.DataTable Get8() {
            return base.Channel.Get8();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get8Async() {
            return base.Channel.Get8Async();
        }
        
        public System.Data.DataTable FindUpdateEmployee(string upnr) {
            return base.Channel.FindUpdateEmployee(upnr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FindUpdateEmployeeAsync(string upnr) {
            return base.Channel.FindUpdateEmployeeAsync(upnr);
        }
        
        public void DeleteEmploye(string delnr) {
            base.Channel.DeleteEmploye(delnr);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeAsync(string delnr) {
            return base.Channel.DeleteEmployeAsync(delnr);
        }
        
        public void AddEmployee(string sosnr, string name, string adress, string lastname, string worktitle) {
            base.Channel.AddEmployee(sosnr, name, adress, lastname, worktitle);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle) {
            return base.Channel.AddEmployeeAsync(sosnr, name, adress, lastname, worktitle);
        }
        
        public void UpdateEmployee(string sosnr, string name, string adress, string lastname, string worktitle) {
            base.Channel.UpdateEmployee(sosnr, name, adress, lastname, worktitle);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle) {
            return base.Channel.UpdateEmployeeAsync(sosnr, name, adress, lastname, worktitle);
        }
        
        public object[] objects() {
            return base.Channel.objects();
        }
        
        public System.Threading.Tasks.Task<object[]> objectsAsync() {
            return base.Channel.objectsAsync();
        }
        
        public object[] dsToArray() {
            return base.Channel.dsToArray();
        }
        
        public System.Threading.Tasks.Task<object[]> dsToArrayAsync() {
            return base.Channel.dsToArrayAsync();
        }
        
        public System.Data.DataTable FindEmployee(string sosnr) {
            return base.Channel.FindEmployee(sosnr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FindEmployeeAsync(string sosnr) {
            return base.Channel.FindEmployeeAsync(sosnr);
        }
    }
}
