//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get4", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get5", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get6", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get6Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get7", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get7();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get7", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get7Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get8", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get8();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get8", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get8Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get9();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get9", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get9Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FindUpdateEmployee(string upnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FindUpdateEmployeeAsync(string upnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmploye", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteEmploye(string delnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmploye", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteEmployeAsync(string delnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddEmployee(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task AddEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateEmployee(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] objects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> objectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable FindEmployee(string sosnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FindEmployeeAsync(string sosnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWebsiteHtml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string GetWebsiteHtml(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWebsiteHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWebsiteHtmlAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] objects2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/objects2", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> objects2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sqlstring", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable sqlstring();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sqlstring", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> sqlstringAsync();
        
        // CODEGEN: Parameter 'contents' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        WindowsFormsApplication3.ServiceReference1.UploadResponse Upload(WindowsFormsApplication3.ServiceReference1.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.UploadResponse> UploadAsync(WindowsFormsApplication3.ServiceReference1.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string txtFile(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> txtFileAsync(string filename);
        
        // CODEGEN: Parameter 'JavaUppgiftWebserviceResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JavaUppgiftWebservice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse JavaUppgiftWebservice(WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JavaUppgiftWebservice", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse> JavaUppgiftWebserviceAsync(WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest request);
        
        // CODEGEN: Parameter 'JavaFindUpdateResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JavaFindUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse JavaFindUpdate(WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JavaFindUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse> JavaFindUpdateAsync(WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] contents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string filenamesave;
        
        public UploadRequest() {
        }
        
        public UploadRequest(byte[] contents, string filenamesave) {
            this.contents = contents;
            this.filenamesave = filenamesave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadResponse {
        
        public UploadResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JavaUppgiftWebservice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JavaUppgiftWebserviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int i;
        
        public JavaUppgiftWebserviceRequest() {
        }
        
        public JavaUppgiftWebserviceRequest(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JavaUppgiftWebserviceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JavaUppgiftWebserviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] JavaUppgiftWebserviceResult;
        
        public JavaUppgiftWebserviceResponse() {
        }
        
        public JavaUppgiftWebserviceResponse(string[][] JavaUppgiftWebserviceResult) {
            this.JavaUppgiftWebserviceResult = JavaUppgiftWebserviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JavaFindUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JavaFindUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string upnr;
        
        public JavaFindUpdateRequest() {
        }
        
        public JavaFindUpdateRequest(string upnr) {
            this.upnr = upnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JavaFindUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JavaFindUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] JavaFindUpdateResult;
        
        public JavaFindUpdateResponse() {
        }
        
        public JavaFindUpdateResponse(string[][] JavaFindUpdateResult) {
            this.JavaFindUpdateResult = JavaFindUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WindowsFormsApplication3.ServiceReference1.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication3.ServiceReference1.WebService2Soap>, WindowsFormsApplication3.ServiceReference1.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Get1() {
            return base.Channel.Get1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get1Async() {
            return base.Channel.Get1Async();
        }
        
        public System.Data.DataTable Get2() {
            return base.Channel.Get2();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get2Async() {
            return base.Channel.Get2Async();
        }
        
        public System.Data.DataTable Get3() {
            return base.Channel.Get3();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get3Async() {
            return base.Channel.Get3Async();
        }
        
        public System.Data.DataTable Get4() {
            return base.Channel.Get4();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get4Async() {
            return base.Channel.Get4Async();
        }
        
        public System.Data.DataTable Get5() {
            return base.Channel.Get5();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get5Async() {
            return base.Channel.Get5Async();
        }
        
        public System.Data.DataTable Get6() {
            return base.Channel.Get6();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get6Async() {
            return base.Channel.Get6Async();
        }
        
        public System.Data.DataTable Get7() {
            return base.Channel.Get7();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get7Async() {
            return base.Channel.Get7Async();
        }
        
        public System.Data.DataTable Get8() {
            return base.Channel.Get8();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get8Async() {
            return base.Channel.Get8Async();
        }
        
        public System.Data.DataTable Get9() {
            return base.Channel.Get9();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get9Async() {
            return base.Channel.Get9Async();
        }
        
        public System.Data.DataTable FindUpdateEmployee(string upnr) {
            return base.Channel.FindUpdateEmployee(upnr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FindUpdateEmployeeAsync(string upnr) {
            return base.Channel.FindUpdateEmployeeAsync(upnr);
        }
        
        public void DeleteEmploye(string delnr) {
            base.Channel.DeleteEmploye(delnr);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeAsync(string delnr) {
            return base.Channel.DeleteEmployeAsync(delnr);
        }
        
        public void AddEmployee(string sosnr, string name, string adress, string lastname, string worktitle) {
            base.Channel.AddEmployee(sosnr, name, adress, lastname, worktitle);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle) {
            return base.Channel.AddEmployeeAsync(sosnr, name, adress, lastname, worktitle);
        }
        
        public void UpdateEmployee(string sosnr, string name, string adress, string lastname, string worktitle) {
            base.Channel.UpdateEmployee(sosnr, name, adress, lastname, worktitle);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(string sosnr, string name, string adress, string lastname, string worktitle) {
            return base.Channel.UpdateEmployeeAsync(sosnr, name, adress, lastname, worktitle);
        }
        
        public object[] objects() {
            return base.Channel.objects();
        }
        
        public System.Threading.Tasks.Task<object[]> objectsAsync() {
            return base.Channel.objectsAsync();
        }
        
        public System.Data.DataTable FindEmployee(string sosnr) {
            return base.Channel.FindEmployee(sosnr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FindEmployeeAsync(string sosnr) {
            return base.Channel.FindEmployeeAsync(sosnr);
        }
        
        public string GetWebsiteHtml(string url) {
            return base.Channel.GetWebsiteHtml(url);
        }
        
        public System.Threading.Tasks.Task<string> GetWebsiteHtmlAsync(string url) {
            return base.Channel.GetWebsiteHtmlAsync(url);
        }
        
        public object[] objects2() {
            return base.Channel.objects2();
        }
        
        public System.Threading.Tasks.Task<object[]> objects2Async() {
            return base.Channel.objects2Async();
        }
        
        public System.Data.DataTable sqlstring() {
            return base.Channel.sqlstring();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> sqlstringAsync() {
            return base.Channel.sqlstringAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication3.ServiceReference1.UploadResponse WindowsFormsApplication3.ServiceReference1.WebService2Soap.Upload(WindowsFormsApplication3.ServiceReference1.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public void Upload(byte[] contents, string filenamesave) {
            WindowsFormsApplication3.ServiceReference1.UploadRequest inValue = new WindowsFormsApplication3.ServiceReference1.UploadRequest();
            inValue.contents = contents;
            inValue.filenamesave = filenamesave;
            WindowsFormsApplication3.ServiceReference1.UploadResponse retVal = ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).Upload(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.UploadResponse> WindowsFormsApplication3.ServiceReference1.WebService2Soap.UploadAsync(WindowsFormsApplication3.ServiceReference1.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.UploadResponse> UploadAsync(byte[] contents, string filenamesave) {
            WindowsFormsApplication3.ServiceReference1.UploadRequest inValue = new WindowsFormsApplication3.ServiceReference1.UploadRequest();
            inValue.contents = contents;
            inValue.filenamesave = filenamesave;
            return ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).UploadAsync(inValue);
        }
        
        public string txtFile(string filename) {
            return base.Channel.txtFile(filename);
        }
        
        public System.Threading.Tasks.Task<string> txtFileAsync(string filename) {
            return base.Channel.txtFileAsync(filename);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse WindowsFormsApplication3.ServiceReference1.WebService2Soap.JavaUppgiftWebservice(WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest request) {
            return base.Channel.JavaUppgiftWebservice(request);
        }
        
        public string[][] JavaUppgiftWebservice(int i) {
            WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest inValue = new WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest();
            inValue.i = i;
            WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse retVal = ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).JavaUppgiftWebservice(inValue);
            return retVal.JavaUppgiftWebserviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse> WindowsFormsApplication3.ServiceReference1.WebService2Soap.JavaUppgiftWebserviceAsync(WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest request) {
            return base.Channel.JavaUppgiftWebserviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceResponse> JavaUppgiftWebserviceAsync(int i) {
            WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest inValue = new WindowsFormsApplication3.ServiceReference1.JavaUppgiftWebserviceRequest();
            inValue.i = i;
            return ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).JavaUppgiftWebserviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse WindowsFormsApplication3.ServiceReference1.WebService2Soap.JavaFindUpdate(WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest request) {
            return base.Channel.JavaFindUpdate(request);
        }
        
        public string[][] JavaFindUpdate(string upnr) {
            WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest inValue = new WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest();
            inValue.upnr = upnr;
            WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse retVal = ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).JavaFindUpdate(inValue);
            return retVal.JavaFindUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse> WindowsFormsApplication3.ServiceReference1.WebService2Soap.JavaFindUpdateAsync(WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest request) {
            return base.Channel.JavaFindUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.JavaFindUpdateResponse> JavaFindUpdateAsync(string upnr) {
            WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest inValue = new WindowsFormsApplication3.ServiceReference1.JavaFindUpdateRequest();
            inValue.upnr = upnr;
            return ((WindowsFormsApplication3.ServiceReference1.WebService2Soap)(this)).JavaFindUpdateAsync(inValue);
        }
    }
}
